### ISSUE TITLE
Item issue

### ISSUE THREAD

**Issue by justinthejaguar** [wintersleepAI/foundry-swnr#26] opened 2022-09-20 19:45 UTC
Item descriptions for the item type disappear after update in v10.

**Comment by CptSauceBucket** [comment] 2022-09-26 21:46
I'm having a similar issue. Wracked my head at first thinking it was a module clash.

**Comment by Cup-of-Coffee** [comment] 2022-10-03 14:05
A snippet of the error outputted when you attempt to save a edit. 

![Screenshot 2022-10-03 100412](https://user-images.githubusercontent.com/39238717/193597678-89cdce3d-dea8-418a-80fc-0060db8f0c2e.png)

![Screenshot 2022-10-03 100420](https://user-images.githubusercontent.com/39238717/193597694-29bdb43f-e74d-43d0-98df-c9941c7f6290.png)

**Comment by giuseppe-crea** [comment] 2022-11-30 12:56
Digging around with the debugger I've noticed that the editor.instance reads as null.
![image](https://user-images.githubusercontent.com/7926745/204801756-afcd1146-2a4d-4e9e-82c9-e09396d7b15c.png)

This bug doesn't happen when editing the description of an Actor sheet, there the editor.instance is properly defined, but since I'm not versed in Foundry I don't know what to make of that.

**Comment by giuseppe-crea** [comment] 2022-11-30 21:11
Okay after further research I can confidently say that the issue is the original author's override of activateEditor found here

https://github.com/wintersleepAI/foundry-swnr/blob/992d59e5aa8c096d1a76fb11464d6d570a01a7e5/src/module/items/base-sheet.ts#L37-L54

Deleting the method entirely restores functionality to item sheets. I'm not sure why this override exists as it does not seem to do anything on top of the default functionality of the activateEditor method, but I would need to test it out before making a PR to remove it.

**Comment by wintersleepAI** [comment] 2023-01-04 16:00
Will be resolved in next release. Thanks @giuseppe-crea  again!

**Closed by wintersleepAI** 2023-01-04 16:00 UTC
